config:
  target: 'http://localhost:3001'
  phases:
    - duration: 60
      arrivalRate: 10
      rampTo: 1000
      name: "Warm up the application"
    - duration: 30
      arrivalRate: 1000
      name: "Sustained max load"
scenarios:
  - flow:
    - get:
        url: "/rooms/{{$randomNumber(1,10000)}}"
    - get:
        url: "/rooms/{{$randomNumber(1,10000)}}/images"
    - post:
        url: "/rooms/{{$randomNumber(1,10000)}}/images"
