config:
  target: 'http://localhost:3001'
  phases:
    - duration: 30
      arrivalRate: 10
      rampTo: 100
      name: "Warm up the application"
    - duration: 60
      arrivalRate: 100
      name: "Sustained max load"
scenarios:
  - flow:
    - get:
        url: "/rooms/{{$randomNumber(0,9999999)}}/images"
    - post:
        url: "/rooms/{{$randomNumber(0,9999999)}}/images"
        json:
          url: "test"
          description: "test"
